In [1]:
train_text=[
    "Twinkle, twinkle, little star",
    "How I wonder what you are",
    "Up above the world so high",
    "Like a diamond in the sky",
    "Twinkle, twinkle, little star",
    "How I wonder what you are",
]

raw text cant fed in ml model

most ml algorithm except numerical feature vectors with a fixed size

skl provides utlities for the most common way to extract numerical features from text

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import set_config
set_config(print_changed_only=False)
Bow=CountVectorizer()

In [3]:
Bow.fit(train_text) #learn the vocabulary

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [4]:
#examine the fitted vocabulary 一個一個斷詞
Bow.get_feature_names()

['above',
 'are',
 'diamond',
 'high',
 'how',
 'in',
 'like',
 'little',
 'sky',
 'so',
 'star',
 'the',
 'twinkle',
 'up',
 'what',
 'wonder',
 'world',
 'you']

In [5]:
#transform to 2D arrray dtm matrix
train_text_dtm=Bow.transform(train_text)
train_text_dtm

<6x18 sparse matrix of type '<class 'numpy.int64'>'
	with 27 stored elements in Compressed Sparse Row format>

In [6]:
type(train_text_dtm) #check type, sparse matrix

scipy.sparse.csr.csr_matrix

In [7]:
print(train_text_dtm)

  (0, 7)	1
  (0, 10)	1
  (0, 12)	2
  (1, 1)	1
  (1, 4)	1
  (1, 14)	1
  (1, 15)	1
  (1, 17)	1
  (2, 0)	1
  (2, 3)	1
  (2, 9)	1
  (2, 11)	1
  (2, 13)	1
  (2, 16)	1
  (3, 2)	1
  (3, 5)	1
  (3, 6)	1
  (3, 8)	1
  (3, 11)	1
  (4, 7)	1
  (4, 10)	1
  (4, 12)	2
  (5, 1)	1
  (5, 4)	1
  (5, 14)	1
  (5, 15)	1
  (5, 17)	1

In [8]:
#

In [9]:
train_text_dtm.toarray() #turn to Dense matrix

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1]])

In [10]:
import pandas as pd 
pd.DataFrame(train_text_dtm.toarray(),columns=Bow.get_feature_names())

,above,are,diamond,high,how,in,like,little,sky,so,star,the,twinkle,up,what,wonder,world,you
0,0,0,0,0,0,0,0,1,0,0,1,0,2,0,0,0,0,0
1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1
2,1,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,1,0
3,0,0,1,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,1,0,2,0,0,0,0,0
5,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1

In [11]:
# each token is a feature
#all token frequency for a given document is a multivariate sample
#corpus -- row token--col
#vecotrize the general process turn into numerical feature vectors
#bag of n-grams. ignoring the position

In [12]:
Bow_2=CountVectorizer(stop_words='english') #remove stopwords

In [13]:
Bow_2.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [14]:
Bow_2.get_feature_names()

['diamond',
 'high',
 'like',
 'little',
 'sky',
 'star',
 'twinkle',
 'wonder',
 'world']

In [15]:
#transform to 2D arrray dtm matrix
train_text_dtm_2=Bow_2.transform(train_text)
train_text_dtm_2

<6x9 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [16]:
pd.DataFrame(train_text_dtm_2.toarray(),columns=Bow_2.get_feature_names())

   diamond  high  like  little  sky  star  twinkle  wonder  world
0        0     0     0       1    0     1        2       0      0
1        0     0     0       0    0     0        0       1      0
2        0     1     0       0    0     0        0       0      1
3        1     0     1       0    1     0        0       0      0
4        0     0     0       1    0     1        2       0      0
5        0     0     0       0    0     0        0       1      0

In [17]:
#ngram_range(min,max),default(1,1) 詞兩兩相鄰

In [18]:
Bow_3=CountVectorizer(ngram_range=(1,2))

In [19]:
Bow_3.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 2), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [20]:
Bow_3.get_feature_names() #除了單個外，還有兩倆

['above',
 'above the',
 'are',
 'diamond',
 'diamond in',
 'high',
 'how',
 'how wonder',
 'in',
 'in the',
 'like',
 'like diamond',
 'little',
 'little star',
 'sky',
 'so',
 'so high',
 'star',
 'the',
 'the sky',
 'the world',
 'twinkle',
 'twinkle little',
 'twinkle twinkle',
 'up',
 'up above',
 'what',
 'what you',
 'wonder',
 'wonder what',
 'world',
 'world so',
 'you',
 'you are']

In [21]:
train_text_dtm_3=Bow_3.transform(train_text)
train_text_dtm_3

<6x34 sparse matrix of type '<class 'numpy.int64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [22]:
pd.DataFrame(train_text_dtm_3.toarray(),columns=Bow_3.get_feature_names())

,above,above the,are,diamond,diamond in,high,how,how wonder,in,in the,...,up,up above,what,what you,wonder,wonder what,world,world so,you,you are
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,1,1,0,0,...,0,0,1,1,1,1,0,0,1,1
2,1,1,0,0,0,1,0,0,0,0,...,1,1,0,0,0,0,1,1,0,0
3,0,0,0,1,1,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,1,0,0,0,1,1,0,0,...,0,0,1,1,1,1,0,0,1,1

In [23]:
#include 1-3 gram
Bow_4=CountVectorizer(ngram_range=(1,3))

In [24]:
Bow_4.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 3), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [25]:
Bow_4.get_feature_names() #除了單個外，還有兩倆

['above',
 'above the',
 'above the world',
 'are',
 'diamond',
 'diamond in',
 'diamond in the',
 'high',
 'how',
 'how wonder',
 'how wonder what',
 'in',
 'in the',
 'in the sky',
 'like',
 'like diamond',
 'like diamond in',
 'little',
 'little star',
 'sky',
 'so',
 'so high',
 'star',
 'the',
 'the sky',
 'the world',
 'the world so',
 'twinkle',
 'twinkle little',
 'twinkle little star',
 'twinkle twinkle',
 'twinkle twinkle little',
 'up',
 'up above',
 'up above the',
 'what',
 'what you',
 'what you are',
 'wonder',
 'wonder what',
 'wonder what you',
 'world',
 'world so',
 'world so high',
 'you',
 'you are']

In [26]:
train_text_dtm_4=Bow_4.transform(train_text)
train_text_dtm_4

<6x46 sparse matrix of type '<class 'numpy.int64'>'
	with 67 stored elements in Compressed Sparse Row format>

In [27]:
pd.DataFrame(train_text_dtm_4.toarray(),columns=Bow_4.get_feature_names())

,above,above the,above the world,are,diamond,diamond in,diamond in the,high,how,how wonder,...,what you,what you are,wonder,wonder what,wonder what you,world,world so,world so high,you,you are
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,1,1,...,1,1,1,1,1,0,0,0,1,1
2,1,1,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,1,1,0,0
3,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,1,0,0,0,0,1,1,...,1,1,1,1,1,0,0,0,1,1

In [28]:
#ignore terms that appear in over 80% of the documents
bow_max=CountVectorizer(max_df=0.8)

In [29]:
bow_max.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=0.8, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [30]:
bow_max.get_feature_names()

['above',
 'are',
 'diamond',
 'high',
 'how',
 'in',
 'like',
 'little',
 'sky',
 'so',
 'star',
 'the',
 'twinkle',
 'up',
 'what',
 'wonder',
 'world',
 'you']

In [31]:
train_text_dtm_5=bow_max.transform(train_text)
train_text_dtm_5

<6x18 sparse matrix of type '<class 'numpy.int64'>'
	with 27 stored elements in Compressed Sparse Row format>

In [32]:
pd.DataFrame(train_text_dtm_5.toarray(),columns=bow_max.get_feature_names())

,above,are,diamond,high,how,in,like,little,sky,so,star,the,twinkle,up,what,wonder,world,you
0,0,0,0,0,0,0,0,1,0,0,1,0,2,0,0,0,0,0
1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1
2,1,0,0,1,0,0,0,0,0,1,0,1,0,1,0,0,1,0
3,0,0,1,0,0,1,1,0,1,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,1,0,2,0,0,0,0,0
5,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,1

In [33]:
#至少出現幾次，下限
bow_min=CountVectorizer(min_df=2)

In [34]:
bow_min.fit(train_text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=2,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [35]:
bow_min.get_feature_names()

['are', 'how', 'little', 'star', 'the', 'twinkle', 'what', 'wonder', 'you']

In [36]:
train_text_dtm_6=bow_min.transform(train_text)
train_text_dtm_6

<6x9 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [37]:
pd.DataFrame(train_text_dtm_6.toarray(),columns=bow_min.get_feature_names())

   are  how  little  star  the  twinkle  what  wonder  you
0    0    0       1     1    0        2     0       0    0
1    1    1       0     0    0        0     1       1    1
2    0    0       0     0    1        0     0       0    0
3    0    0       0     0    1        0     0       0    0
4    0    0       1     1    0        2     0       0    0
5    1    1       0     0    0        0     1       1    1

In [38]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
tfidf=TfidfVectorizer(stop_words='english')

In [40]:
tfidf.fit(train_text)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=1.0, max_features=None,
                min_df=1, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [41]:
tfidf.get_feature_names()

['diamond',
 'high',
 'like',
 'little',
 'sky',
 'star',
 'twinkle',
 'wonder',
 'world']

In [42]:
train_text_dtm_7=tfidf.transform(train_text)
train_text_dtm_7

<6x9 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [43]:
pd.DataFrame(train_text_dtm_7.toarray(),columns=tfidf.get_feature_names())

,diamond,high,like,little,sky,star,twinkle,wonder,world
0,0.00000,0.000000,0.00000,0.408248,0.00000,0.408248,0.816497,0.0,0.000000
1,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,1.0,0.000000
2,0.00000,0.707107,0.00000,0.000000,0.00000,0.000000,0.000000,0.0,0.707107
3,0.57735,0.000000,0.57735,0.000000,0.57735,0.000000,0.000000,0.0,0.000000
4,0.00000,0.000000,0.00000,0.408248,0.00000,0.408248,0.816497,0.0,0.000000
5,0.00000,0.000000,0.00000,0.000000,0.00000,0.000000,0.000000,1.0,0.000000

In [44]:
#compare to unigram
pd.DataFrame(train_text_dtm_2.toarray(),columns=Bow_2.get_feature_names())

   diamond  high  like  little  sky  star  twinkle  wonder  world
0        0     0     0       1    0     1        2       0      0
1        0     0     0       0    0     0        0       1      0
2        0     1     0       0    0     0        0       0      1
3        1     0     1       0    1     0        0       0      0
4        0     0     0       1    0     1        2       0      0
5        0     0     0       0    0     0        0       1      0

In [45]:
#predict fake review

In [46]:
import pandas as pd

In [47]:
movie=pd.read_csv('movie_review.csv')

In [48]:
movie.head()

                                                text label
0  a brisk , reverent , and subtly different sequ...  REAL
1  one of the more irritating cartoons you will s...  FAKE
2  none of this so-called satire has any sting to...  FAKE
3  the most brilliant and brutal uk crime film si...  REAL
4                   an asian neo-realist treasure .   REAL

In [49]:
movie.shape

(8431, 2)

In [50]:
movie.label.value_counts()

REAL    4216
FAKE    4215
Name: label, dtype: int64

In [51]:
movie['new_label']=movie.label.map({'FAKE':0,'REAL':1})

In [52]:
movie.head()

                                                text label  new_label
0  a brisk , reverent , and subtly different sequ...  REAL          1
1  one of the more irritating cartoons you will s...  FAKE          0
2  none of this so-called satire has any sting to...  FAKE          0
3  the most brilliant and brutal uk crime film si...  REAL          1
4                   an asian neo-realist treasure .   REAL          1

In [53]:
X=movie.text
y=movie.new_label
print(X.shape)
print(y.shape)

(8431,)
(8431,)

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1)
print(X_train.shape)
print(X_test.shape)

(6323,)
(2108,)

In [55]:
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
bow=CountVectorizer(stop_words='english') #remove stopwords

In [57]:
bow.fit(X_train)
X_train_dtm=bow.transform(X_train)

In [58]:
X_train_dtm

<6323x14011 sparse matrix of type '<class 'numpy.int64'>'
	with 61447 stored elements in Compressed Sparse Row format>

In [59]:
X_test_dtm=bow.transform(X_test)

In [60]:
X_test_dtm

<2108x14011 sparse matrix of type '<class 'numpy.int64'>'
	with 17914 stored elements in Compressed Sparse Row format>

In [61]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [62]:
lr.fit(X_train_dtm,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [63]:
y_pred=lr.predict(X_test_dtm)

In [64]:
from sklearn import metrics
metrics.accuracy_score(y_test,y_pred)

0.7495256166982922

In [65]:
tfidf=TfidfVectorizer(stop_words='english')

In [66]:
tfidf.fit(X_train)
X_train_dtm2=tfidf.transform(X_train)

In [67]:
X_train_dtm2

<6323x14011 sparse matrix of type '<class 'numpy.float64'>'
	with 61447 stored elements in Compressed Sparse Row format>

In [68]:
X_test_dtm2=tfidf.transform(X_test)
X_test_dtm2

<2108x14011 sparse matrix of type '<class 'numpy.float64'>'
	with 17914 stored elements in Compressed Sparse Row format>

In [69]:
lr.fit(X_train_dtm2,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [70]:
y_pred=lr.predict(X_test_dtm2)

In [71]:
metrics.accuracy_score(y_test,y_pred) #準確率高一點

0.7518975332068312

In [72]:
#sentiment analysis

In [73]:
pip install textblob

Requirement already satisfied: textblob in ./opt/anaconda3/lib/python3.9/site-packages (0.17.1)
Requirement already satisfied: nltk>=3.1 in ./opt/anaconda3/lib/python3.9/site-packages (from textblob) (3.6.5)
Requirement already satisfied: click in ./opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (8.0.3)
Requirement already satisfied: joblib in ./opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (1.1.0)
Requirement already satisfied: regex>=2021.8.3 in ./opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (2021.8.3)
Requirement already satisfied: tqdm in ./opt/anaconda3/lib/python3.9/site-packages (from nltk>=3.1->textblob) (4.62.3)
Note: you may need to restart the kernel to use updated packages.

In [74]:
from textblob import TextBlob
pol=lambda x: TextBlob(x).sentiment.polarity#主觀
sub=lambda x: TextBlob(x).sentiment.subjectivity #客觀

movie['polarity']=movie['text'].apply(pol)
movie['subjectivity']=movie['text'].apply(sub)

movie

,text,label,new_label,polarity,subjectivity
0,"a brisk , reverent , and subtly different sequ...",REAL,1,0.000000,0.600000
1,one of the more irritating cartoons you will s...,FAKE,0,0.050000,0.650000
2,none of this so-called satire has any sting to...,FAKE,0,-0.300000,0.950000
3,the most brilliant and brutal uk crime film si...,REAL,1,0.101389,0.500000
4,an asian neo-realist treasure .,REAL,1,0.000000,0.000000
...,...,...,...,...,...
8426,"[a] rare , beautiful film .",REAL,1,0.575000,0.950000
8427,"as any creature-feature fan knows , when you c...",REAL,1,0.238095,0.523810
8428,heartwarming here relies less on forced air th...,REAL,1,0.166667,0.616667
8429,"a poignant , artfully crafted meditation on mo...",REAL,1,0.000000,0.500000
8430,griffiths proves she's that rare luminary who ...,REAL,1,0.200000,0.300000